### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#10]
Nunca usamos los componente Text, en cambio usamos uno que creamos para mantener la misma typografia en todos los text y que despues no haya inconsistencias entre las pantallas.

En este momento el componente no lo tenes, pero es para que vayas sabiendo, ya lo vamos a agregar.

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/components/Card.js#L13

**Comment by MeliAlbu** [comment]
Entendido, gracias!
