### ISSUE TITLE
Destructurar las props

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#11]
Siempre es bueno destructurar las props:

`const { image } = this.props`

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/components/Card.js#L13

**Comment by MeliAlbu** [comment]
Listo, lo cambié. Quedo así:

export default class Card extends Component {
    render() 
    
    {const {name} = this.props
        return (    
           
            <View style={styles.Card}>
                <Image style=
                {styles.DrinkImage}
                source={{ uri: this.props.urlImage }} />
                <Text style={styles.DrinkName}>{name}</Text>
                <Text>{this.props.idItem}</Text>
            </View>
        )
    }
}
