### ISSUE TITLE
Mejoras de codigo

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#13]
Esto es una sonsera, podrias guardar esa misma var antes del this.setState, para poder usarla ahi y mas abajo

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/screens/CocktailFinderScreen.js#L31

**Comment by MeliAlbu** [comment]
Hecho! Quedo así:

class CocktailFinderScreen extends React.Component<Props> {
  state = {
    value: ""
  };

  TextFilter = event => {
    const text = event.nativeEvent.text;

    this.setState({
      value: text
    });

    if (text.length >= 3) {
      this.getDrinksFromApi(text);
    } else {
      const { getCocktailsConnected } = this.props;
      const { deleteCocktailsConnected } = this.props;
      deleteCocktailsConnected("");
    }
  };

Gracias!
