### ISSUE TITLE
Funciones tipo lambda

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#14]
Para no tener que bindiar las funciones posteriormente, te recomiendo que las uses como lambda unicamente a las que no son de la clase de RN (Ej, componentDidMount, componendDidUnmount, etc). entonces a su vez diferencias cuales vienen heredadas y cuales creaste vos

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/screens/CocktailFinderScreen.js#L45

**Comment by MeliAlbu** [comment]
Entendido, gracias!
