### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#17]
No esta mal como lo estas implementando, pero para que sepas, en varios proyectos donde ocupanos RNavigation tenemos una carpeta en src que se llama navigation donde tenemos las rutas, los types, y las funciones mas comunes.

Luego te lo mostramos, no tenes que cambiar nada

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/screens/Home.js#L31

**Comment by MeliAlbu** [comment]
Entendido, gracias!
