### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#18]
Algo indispensable es arreglar Prettier, tenemos que revisar por que no esta funcionando correctamente :c

**Comment by edgarbonillag** [comment]
@LcsGrz Según veo el eslint no está configurado para este proyecto, igual no sé si sea del todo necesario para un challenge ponerlos a configurar el eslint.

**Comment by MeliAlbu** [comment]
Hola chicos, es verdad. Ya lo arreglé! Gracias!
