### ISSUE TITLE
Cambiar MAP por flatlist

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#19]
No es bueno usar un map para generar un scroll con conponentes, te recomiendo usar esto

https://www.google.com/search?client=firefox-b-d&q=flatlist+react+native

Ademas de mejoras en cuando a componente, hay metodos que son muy utiles

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/screens/CocktailFinderScreen.js#L61

**Comment by MeliAlbu** [comment]
Actualizado, gracias!
