### ISSUE TITLE
Imagenes

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#2]
Las imagenes, fuentes, iconos (Todo lo que sean assets) deben ir en una carpeta que se llame `assets` dentro de SRC

Recomiendo ordenar por tipos, por ejemplo si tenes fuentes
Creas la carpeta fonts, lo mismo para images, icons, vectors, lo que exista.

Nososotros tenemos siempre un archivito en el root de assets que se llama `index.js` donde dentro importamos y exportamos todas las imagenes de esta forma

> export { default as like } from './icons/like.png';

para luego en las screens llamarlo asi

> import { like } from '../../assets/images';

**Comment by MeliAlbu** [comment]
Listo, ya subí los cambios. Gracias!!
