### ISSUE TITLE
Todo en inglés

### ISSUE THREAD

**Issue by edgarbonillag** [MeliAlbu/Challenge-NextDots#20]
https://github.com/MeliAlbu/Challenge-NextDots/blob/520dcf50f5023ca569f239fdeed027760ebe3e65/src/store/types.js#L1

Cambiar `OBTUVE_DATOS` por `GET_DATA_SUCCESS` para dar un ejemplo.
En general, cambiar todo lo que esté en español, a inglés.

**Comment by MeliAlbu** [comment]
Listo, ya lo actualicé a inglés. Gracias!
