### ISSUE TITLE
Uso adecuado de 'try catch' con 'fetch'.

### ISSUE THREAD

**Issue by edgarbonillag** [MeliAlbu/Challenge-NextDots#21]
https://github.com/MeliAlbu/Challenge-NextDots/blob/520dcf50f5023ca569f239fdeed027760ebe3e65/src/store/actionsCocktails.js#L17

Al usar el fetch de este modo ( `.then().catch()` ) no va a tener en realidad efecto alguno dentro del `try catch`. El modo correcto de usarlo sería más o menos así: 
```
exampleFunction = async () => {
  try {
     const response = await fetch(bla bla bla);
     const responseJson = await response.json();
     dispatch({ bla bla bla });
  } catch (error) {
    //
  }
}
```
Si algo malo sucede en alguno de los dos `await` salta automáticamente al catch y no ejecuta la siguiente línea.

**Comment by MeliAlbu** [comment]
Actualizado, gracias por la explicación!
