### ISSUE TITLE
Centralizar api endpoint

### ISSUE THREAD

**Issue by edgarbonillag** [MeliAlbu/Challenge-NextDots#22]
https://github.com/MeliAlbu/Challenge-NextDots/blob/520dcf50f5023ca569f239fdeed027760ebe3e65/src/store/actionsCocktails.js#L18

Es bueno centralizar en endpoint. Ejemplo, puedes crear un archivo `config` en la raíz de `src` donde definas una constante con el endpoint y luego importes el endpoint donde lo necesitas usar

**Comment by MeliAlbu** [comment]
Entendido, gracias!!
