### ISSUE TITLE
Estructura general de archivos y carpetas

### ISSUE THREAD

**Issue by edgarbonillag** [MeliAlbu/Challenge-NextDots#23]
En general hacer lo siguiente, doy el ejemplo para la carpeta de components

```
components/
  Card/
    index.js
    Card.js
    styles.js
  Input/
    index.js
    Card.js
    styles.js
  index.js
```

En el archivo `index.js` de cada componente iría algo como así:
`export { default } from './Card';`

Y en el archivo `index.js` de la carpeta `Components` iría algo así:
```
export { default as Card } from './Card';
export { default as Input } from './Input';
```

Y cuando tengas que llamar a un componente en una screen sería algo como:
`import { Card }  from '../components'`

NOTA: Este es el ejemplo para los componentes, hay que hacerlo para las screens, las imágenes, las actions y los reducers, cada cosa en una carpeta diferente con su propio `index.js`

**Comment by MeliAlbu** [comment]
Solucionado! Gracias.
