### ISSUE TITLE
Componentes

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#3]
Los componentes siempre van en la carpeta `components` en src, esta bien como lo hiciste. pero como sugerencia es mejor que por cada componente agreges una carpeta 

EJ:
Creas el componente Card, bueno crea una carpeta que tenga ese nombre y dentro los archivos
`styles.js` & `index.js`

Donde en styles estaran unicamente los estilos, que en index vas a importar y usar
Y en index va a estar todo tu componente

Para mi es mucho mas comodo tener separado los estilos del componente.

-------

Se agrega el archivo index para hacer lo mismo que el assets de imagenes.
Se va a crear un archivo index.js dentro del root de componentes donde vas a importar todos los componentes y volverlos a exportar.
Para no duplicar info, ver issue: https://github.com/MeliAlbu/Challenge-NextDots/issues/2

**Comment by MeliAlbu** [comment]
Listo, ya separé los estilos. Gracias!
