### ISSUE TITLE
Mover estilo a su archivo styles

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#4]
Move los estilos a un archivo styles.js
Luego revisa este issue para terminar de completar https://github.com/MeliAlbu/Challenge-NextDots/issues/3

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/components/Card.js#L19

**Comment by MeliAlbu** [comment]
Hecho! Gracias.
