### ISSUE TITLE
Mejoras en styles de un componente

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#6]
No esta mal, pero hay una forma mejor de agregar varios estilos a un componente.
Los estilos se pueden pasar como objetos, o como un array de objetos.

Entonces esto te quedaria asi: `style={[styles.input, props.style]}`

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/components/Input.js#L7

**Comment by MeliAlbu** [comment]
Mejorado! Gracias.
