### ISSUE TITLE
Colores en su index

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#7]
Por lo general en ND, para tener los mismos colores en toda la app y si es necesario un cambio sea rapido de hacer, tenemos un index de colores.

Habria que crear la carpeta `theme` en `src` donde dentro crear el archivo `colors.js`
Ahi dentro agregas algo como esto:

export defult {
  transparent: 'rgba(255, 255, 255, 0)',
  white: '#FFFFFF',
};

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/components/Input.js#L16

----

A mi cuando entre me dijieron que los colores siempre este en HEX, no se si fue para que queden todos con el mismo tipo, o por algo en especial, esta parte la dejo abierta para debatir, no me parece que sea algo 100% necesario

**Comment by LcsGrz** [comment]
Me olvide agregar como usarlo

import colors from `RUTA_ABSOLUTA`

`colors.white`

**Comment by MeliAlbu** [comment]
Listo, ya estan todos el theme/ colors.js. Gracias!
