### ISSUE TITLE
responsiveSize

### ISSUE THREAD

**Issue by LcsGrz** [MeliAlbu/Challenge-NextDots#8]
Se que no tenes la funcion `responsiveSize` pero es algo que me gustaria arreglar ya que nos ayuda desde siempre y es muy importante.

Para todos los estilos que lleven medidas en PX agregamos esa funcion para que se adapte a todos los dispositivos.

es facil de usar, solo hay que pasarle por parametro el numero y retorna el numero adaptado a la pantalla.

No es algo para ver ahora, si no que hay que esperar a la reunion asi creamos los archivos y lo vemos bien

https://github.com/MeliAlbu/Challenge-NextDots/blob/37d7918186ab2b8a753fcacf749f3fe42600dfd6/src/components/Input.js#L14

**Comment by MeliAlbu** [comment]
Listo, ya agregué la función. Gracias!
